package d220317;// Generated by Selenium IDE

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import java.util.*;

public class AddRemoveElementsTest extends BaseTest {

    @Test
    public void addRemoveElements() {

        driver.findElement(By.linkText("Add/Remove Elements")).click();
        driver.findElement(By.cssSelector("button")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".added-manually"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.cssSelector(".added-manually")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".added-manually"));
            assert (elements.size() == 0);
        }
    }
}